version: 2
jobs:
  build:
    docker:
      - image: openjdk:8
    steps:
      - restore_cache:
          key: sbt-cache
      - checkout
      - run:
          name: Install sbt
          command: |
            curl -Ls https://git.io/sbt > /usr/local/bin/sbt
            chmod u+x /usr/local/bin/sbt
      - run:
          command: sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck
      - run:
          command: sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  webpush-testing-service:
      docker:
        - image: nokamoto13/webpush-testing-service:0.0.0
      steps:
        - restore_cache:
            key: sbt-cache-webpush-testing-service
        - run:
            command: apt-get install -y git
        - checkout
        - run:
            name: Checkout submodule
            command: |
              git submodule init
              git submodule update --remote
        - run:
            command: xvfb-run /webpush-testing-service/bin/webpush-testing-service
            background: yes
        - run:
            command: sbt webpush-testing-service:test
        - save_cache:
            key: sbt-cache-webpush-testing-service
            paths:
              - "~/.ivy2/cache"
              - "~/.sbt"
              - "~/.m2"
  publish:
    docker:
      - image: openjdk:8
    steps:
      - restore_cache:
          key: sbt-cache
      - checkout
      - run:
          name: Install sbt
          command: |
            curl -Ls https://git.io/sbt > /usr/local/bin/sbt
            chmod u+x /usr/local/bin/sbt
      - run:
          name: sbt publishSigned
          command: |
            mkdir -p ~/.sbt/gpg
            echo $GPG_SECRET_KEY | base64 --decode > ~/.sbt/gpg/secring.asc
            sbt publishSigned
workflows:
  version: 2
  ci:
    jobs:
      - build
      - webpush-testing-service
      - publish:
          requires:
            - build
            - webpush-testing-service
